# Generated by Django 2.0.3 on 2020-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('generatedTimestamp', models.DateTimeField(null=True)),
                ('recievedTimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempInternal', models.FloatField(null=True)),
                ('humInternal', models.FloatField(null=True)),
                ('tempCab', models.FloatField(null=True)),
                ('humCab', models.FloatField(null=True)),
                ('batteryV', models.FloatField(null=True)),
                ('batteryIP', models.FloatField(null=True)),
                ('batteryIN', models.FloatField(null=True)),
                ('SoC', models.FloatField(null=True)),
                ('PVV', models.FloatField(null=True)),
                ('PVI', models.FloatField(null=True)),
                ('lightPWM', models.IntegerField(null=True)),
                ('bInverter', models.BooleanField(default=False)),
                ('bUVLO', models.BooleanField(default=False)),
                ('bFridge', models.BooleanField(default=False)),
                ('generatedTimestamp', models.DateTimeField(null=True)),
                ('recievedTimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempExternal', models.FloatField(null=True)),
                ('humExternal', models.FloatField(null=True)),
                ('generatedTimestamp', models.DateTimeField(null=True)),
                ('recievedTimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
